/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RolRouteImport } from './routes/rol'
import { Route as StockRouteImport } from './routes/stock'
import { Route as VentasRouteImport } from './routes/ventas'
import { Route as AlbaranesIndexRouteImport } from './routes/albaranes.index'
import { Route as AlbaranesAlbaranIdRouteImport } from './routes/albaranes.$albaranId'
import { Route as AlbaranesNuevoRouteImport } from './routes/albaranes.nuevo'
import { Route as IngredientesIngredientIdRouteImport } from './routes/ingredientes.$ingredientId'
import { Route as RecetasIndexRouteImport } from './routes/recetas.index'
import { Route as RecetasRecetaIdRouteImport } from './routes/recetas.$recetaId'
import { Route as RecetasNuevaRouteImport } from './routes/recetas.nueva'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RolRoute = RolRouteImport.update({
  id: '/rol',
  path: '/rol',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const VentasRoute = VentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbaranesIndexRoute = AlbaranesIndexRouteImport.update({
  id: '/albaranes/',
  path: '/albaranes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbaranesAlbaranIdRoute = AlbaranesAlbaranIdRouteImport.update({
  id: '/albaranes/$albaranId',
  path: '/albaranes/$albaranId',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbaranesNuevoRoute = AlbaranesNuevoRouteImport.update({
  id: '/albaranes/nuevo',
  path: '/albaranes/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientesIngredientIdRoute =
  IngredientesIngredientIdRouteImport.update({
    id: '/ingredientes/$ingredientId',
    path: '/ingredientes/$ingredientId',
    getParentRoute: () => rootRouteImport,
  } as any)
const RecetasIndexRoute = RecetasIndexRouteImport.update({
  id: '/recetas/',
  path: '/recetas/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecetasRecetaIdRoute = RecetasRecetaIdRouteImport.update({
  id: '/recetas/$recetaId',
  path: '/recetas/$recetaId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecetasNuevaRoute = RecetasNuevaRouteImport.update({
  id: '/recetas/nueva',
  path: '/recetas/nueva',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rol': typeof RolRoute
  '/stock': typeof StockRoute
  '/ventas': typeof VentasRoute
  '/albaranes/$albaranId': typeof AlbaranesAlbaranIdRoute
  '/albaranes/nuevo': typeof AlbaranesNuevoRoute
  '/ingredientes/$ingredientId': typeof IngredientesIngredientIdRoute
  '/recetas/$recetaId': typeof RecetasRecetaIdRoute
  '/recetas/nueva': typeof RecetasNuevaRoute
  '/albaranes/': typeof AlbaranesIndexRoute
  '/recetas/': typeof RecetasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rol': typeof RolRoute
  '/stock': typeof StockRoute
  '/ventas': typeof VentasRoute
  '/albaranes/$albaranId': typeof AlbaranesAlbaranIdRoute
  '/albaranes/nuevo': typeof AlbaranesNuevoRoute
  '/ingredientes/$ingredientId': typeof IngredientesIngredientIdRoute
  '/recetas/$recetaId': typeof RecetasRecetaIdRoute
  '/recetas/nueva': typeof RecetasNuevaRoute
  '/albaranes': typeof AlbaranesIndexRoute
  '/recetas': typeof RecetasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rol': typeof RolRoute
  '/stock': typeof StockRoute
  '/ventas': typeof VentasRoute
  '/albaranes/$albaranId': typeof AlbaranesAlbaranIdRoute
  '/albaranes/nuevo': typeof AlbaranesNuevoRoute
  '/ingredientes/$ingredientId': typeof IngredientesIngredientIdRoute
  '/recetas/$recetaId': typeof RecetasRecetaIdRoute
  '/recetas/nueva': typeof RecetasNuevaRoute
  '/albaranes/': typeof AlbaranesIndexRoute
  '/recetas/': typeof RecetasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/rol'
    | '/stock'
    | '/ventas'
    | '/albaranes/$albaranId'
    | '/albaranes/nuevo'
    | '/ingredientes/$ingredientId'
    | '/recetas/$recetaId'
    | '/recetas/nueva'
    | '/albaranes/'
    | '/recetas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/rol'
    | '/stock'
    | '/ventas'
    | '/albaranes/$albaranId'
    | '/albaranes/nuevo'
    | '/ingredientes/$ingredientId'
    | '/recetas/$recetaId'
    | '/recetas/nueva'
    | '/albaranes'
    | '/recetas'
  id:
    | '__root__'
    | '/'
    | '/rol'
    | '/stock'
    | '/ventas'
    | '/albaranes/$albaranId'
    | '/albaranes/nuevo'
    | '/ingredientes/$ingredientId'
    | '/recetas/$recetaId'
    | '/recetas/nueva'
    | '/albaranes/'
    | '/recetas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RolRoute: typeof RolRoute
  StockRoute: typeof StockRoute
  VentasRoute: typeof VentasRoute
  AlbaranesAlbaranIdRoute: typeof AlbaranesAlbaranIdRoute
  AlbaranesNuevoRoute: typeof AlbaranesNuevoRoute
  IngredientesIngredientIdRoute: typeof IngredientesIngredientIdRoute
  RecetasRecetaIdRoute: typeof RecetasRecetaIdRoute
  RecetasNuevaRoute: typeof RecetasNuevaRoute
  AlbaranesIndexRoute: typeof AlbaranesIndexRoute
  RecetasIndexRoute: typeof RecetasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rol': {
      id: '/rol'
      path: '/rol'
      fullPath: '/rol'
      preLoaderRoute: typeof RolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventas': {
      id: '/ventas'
      path: '/ventas'
      fullPath: '/ventas'
      preLoaderRoute: typeof VentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albaranes/': {
      id: '/albaranes/'
      path: '/albaranes'
      fullPath: '/albaranes/'
      preLoaderRoute: typeof AlbaranesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albaranes/$albaranId': {
      id: '/albaranes/$albaranId'
      path: '/albaranes/$albaranId'
      fullPath: '/albaranes/$albaranId'
      preLoaderRoute: typeof AlbaranesAlbaranIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albaranes/nuevo': {
      id: '/albaranes/nuevo'
      path: '/albaranes/nuevo'
      fullPath: '/albaranes/nuevo'
      preLoaderRoute: typeof AlbaranesNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredientes/$ingredientId': {
      id: '/ingredientes/$ingredientId'
      path: '/ingredientes/$ingredientId'
      fullPath: '/ingredientes/$ingredientId'
      preLoaderRoute: typeof IngredientesIngredientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recetas/': {
      id: '/recetas/'
      path: '/recetas'
      fullPath: '/recetas/'
      preLoaderRoute: typeof RecetasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recetas/$recetaId': {
      id: '/recetas/$recetaId'
      path: '/recetas/$recetaId'
      fullPath: '/recetas/$recetaId'
      preLoaderRoute: typeof RecetasRecetaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recetas/nueva': {
      id: '/recetas/nueva'
      path: '/recetas/nueva'
      fullPath: '/recetas/nueva'
      preLoaderRoute: typeof RecetasNuevaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RolRoute: RolRoute,
  StockRoute: StockRoute,
  VentasRoute: VentasRoute,
  AlbaranesAlbaranIdRoute: AlbaranesAlbaranIdRoute,
  AlbaranesNuevoRoute: AlbaranesNuevoRoute,
  IngredientesIngredientIdRoute: IngredientesIngredientIdRoute,
  RecetasRecetaIdRoute: RecetasRecetaIdRoute,
  RecetasNuevaRoute: RecetasNuevaRoute,
  AlbaranesIndexRoute: AlbaranesIndexRoute,
  RecetasIndexRoute: RecetasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
