import type { AppState, Ingredient, Recipe, Unit } from './types'

const ing = (
  id: string,
  name: string,
  category: string,
  unit: Unit,
  stock: number,
  minStock: number,
  costPerUnit: number,
): Ingredient => ({ id, name, category, unit, stock, minStock, costPerUnit })

const ingredients: Ingredient[] = [
  ing('macarrones', 'Macarrones', 'Despensa', 'g', 5000, 1500, 0.0021),
  ing('tomate', 'Tomate triturado', 'Despensa', 'g', 7000, 2000, 0.0016),
  ing('cebolla', 'Cebolla', 'Verdura', 'g', 3000, 1000, 0.0012),
  ing('ajo', 'Ajo', 'Verdura', 'g', 250, 100, 0.006),
  ing('aceite', 'Aceite de oliva', 'Despensa', 'ml', 4500, 2000, 0.0072),
  ing('sal', 'Sal', 'Despensa', 'g', 2000, 500, 0.0006),
  ing('leche', 'Leche entera', 'Lácteos', 'ml', 6000, 2000, 0.00085),
  ing('harina', 'Harina de trigo', 'Despensa', 'g', 3500, 1000, 0.0011),
  ing('mantequilla', 'Mantequilla', 'Lácteos', 'g', 900, 500, 0.0072),
  ing('carne', 'Carne picada de ternera', 'Carne', 'g', 2400, 2000, 0.0098),
  ing('queso', 'Queso rallado', 'Lácteos', 'g', 800, 600, 0.0085),
  ing('pan', 'Pan de hamburguesa', 'Panadería', 'ud', 14, 10, 0.32),
  ing('lechuga', 'Lechuga', 'Verdura', 'g', 1500, 500, 0.0035),
  ing('patata', 'Patata', 'Verdura', 'g', 9000, 3000, 0.0011),
  ing('huevo', 'Huevos', 'Lácteos', 'ud', 30, 12, 0.22),
  ing('pimenton', 'Pimentón picante', 'Despensa', 'g', 140, 100, 0.016),
  ing('cola', 'Coca-Cola 33 cl', 'Bebidas', 'ud', 12, 12, 0.58),
  ing('cerveza', 'Cerveza 33 cl', 'Bebidas', 'ud', 6, 12, 0.62),
]

const recipes: Recipe[] = [
  {
    id: 'salsa-tomate',
    name: 'Salsa de tomate casera',
    kind: 'intermediate',
    yieldQty: 2000,
    unit: 'ml',
    price: 0,
    items: [
      { kind: 'ingredient', refId: 'tomate', quantity: 1600 },
      { kind: 'ingredient', refId: 'cebolla', quantity: 250 },
      { kind: 'ingredient', refId: 'ajo', quantity: 20 },
      { kind: 'ingredient', refId: 'aceite', quantity: 120 },
      { kind: 'ingredient', refId: 'sal', quantity: 15 },
    ],
  },
  {
    id: 'bechamel',
    name: 'Bechamel',
    kind: 'intermediate',
    yieldQty: 1000,
    unit: 'ml',
    price: 0,
    items: [
      { kind: 'ingredient', refId: 'leche', quantity: 1000 },
      { kind: 'ingredient', refId: 'harina', quantity: 80 },
      { kind: 'ingredient', refId: 'mantequilla', quantity: 80 },
      { kind: 'ingredient', refId: 'sal', quantity: 5 },
    ],
  },
  {
    id: 'salsa-brava',
    name: 'Salsa brava',
    kind: 'intermediate',
    yieldQty: 500,
    unit: 'ml',
    price: 0,
    items: [
      { kind: 'ingredient', refId: 'tomate', quantity: 300 },
      { kind: 'ingredient', refId: 'pimenton', quantity: 20 },
      { kind: 'ingredient', refId: 'aceite', quantity: 80 },
      { kind: 'ingredient', refId: 'harina', quantity: 25 },
    ],
  },
  {
    id: 'macarrones',
    name: 'Macarrones con carne',
    kind: 'final',
    yieldQty: 1,
    unit: 'ud',
    price: 9.5,
    items: [
      { kind: 'ingredient', refId: 'macarrones', quantity: 120 },
      { kind: 'recipe', refId: 'salsa-tomate', quantity: 150 },
      { kind: 'ingredient', refId: 'carne', quantity: 100 },
      { kind: 'ingredient', refId: 'queso', quantity: 20 },
    ],
  },
  {
    id: 'hamburguesa',
    name: 'Hamburguesa clásica',
    kind: 'final',
    yieldQty: 1,
    unit: 'ud',
    price: 12,
    items: [
      { kind: 'ingredient', refId: 'pan', quantity: 1 },
      { kind: 'ingredient', refId: 'carne', quantity: 180 },
      { kind: 'ingredient', refId: 'queso', quantity: 20 },
      { kind: 'ingredient', refId: 'lechuga', quantity: 20 },
    ],
  },
  {
    id: 'bravas',
    name: 'Patatas bravas',
    kind: 'final',
    yieldQty: 1,
    unit: 'ud',
    price: 6.5,
    items: [
      { kind: 'ingredient', refId: 'patata', quantity: 300 },
      { kind: 'recipe', refId: 'salsa-brava', quantity: 60 },
      { kind: 'ingredient', refId: 'aceite', quantity: 40 },
    ],
  },
  {
    id: 'croquetas',
    name: 'Croquetas caseras (6 uds)',
    kind: 'final',
    yieldQty: 1,
    unit: 'ud',
    price: 8,
    items: [
      { kind: 'recipe', refId: 'bechamel', quantity: 250 },
      { kind: 'ingredient', refId: 'huevo', quantity: 1 },
      { kind: 'ingredient', refId: 'aceite', quantity: 60 },
    ],
  },
  {
    id: 'cola',
    name: 'Coca-Cola',
    kind: 'final',
    yieldQty: 1,
    unit: 'ud',
    price: 2.5,
    items: [{ kind: 'ingredient', refId: 'cola', quantity: 1 }],
  },
]

export const createSeedState = (): AppState => ({
  ingredients: structuredClone(ingredients),
  recipes: structuredClone(recipes),
  notes: [],
  movements: [],
  sales: [],
})
